// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://2j4yiyzgzzasxeht7kgz2zrfgu.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-w7mx4dhzjbe6jepozmia4lplvu",
    "aws_cognito_identity_pool_id": "ap-south-1:28cf10b9-de60-4437-9f6f-6bd2499fdae9",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_mRHBO1nfJ",
    "aws_user_pools_web_client_id": "6iqfvevtdm86g0hupur031ai4t",
    "oauth": {},
    "aws_user_files_s3_bucket": "practitionerdashboarf5fdcfa0525349a88f909a899cc0b6e2-practenv",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_content_delivery_bucket": "practitionerdashboar-20191211152210-hostingbucket-practenv",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "http://practitionerdashboar-20191211152210-hostingbucket-practenv.s3-website.ap-south-1.amazonaws.com"
};


export default awsmobile;
